const animalesData = [
  // Mascotas para adopción - Perros
  {
    imagen: "./assets/dogs/perro1.webp",
    nombre: "Max",
    tipo: "perro",
    categoria: "adopcion",
    edad: "6 meses",
    tamaño: "Mediano",
    personalidad: "Juguetón y amigable",
    nivelEnergia: "Alto",
    requisitos: "Tener espacio para jugar y disponibilidad para paseos diarios",
    ubicacion: "Bogotá",
    costoMensual: 120000,
  },
  {
    imagen: "./assets/dogs/perro2.webp",
    nombre: "Rocky",
    tipo: "perro",
    categoria: "adopcion",
    edad: "4 años",
    tamaño: "Pequeño",
    personalidad: "Amigable y cariñoso",
    nivelEnergia: "Bajo",
    requisitos: "Ambiente tranquilo y visitas veterinarias regulares",
    ubicacion: "Medellín",
    costoMensual: 100000,
  },
  {
    imagen: "./assets/dogs/perro3.webp",
    nombre: "Bella",
    tipo: "perro",
    categoria: "adopcion",
    edad: "5 meses",
    tamaño: "Mediano",
    personalidad: "Dulce y obediente",
    nivelEnergia: "Moderado",
    requisitos: "Familia con tiempo para entrenarla y cuidarla",
    ubicacion: "Cali",
    costoMensual: 110000,
  },
  {
    imagen: "./assets/dogs/perro4.webp",
    nombre: "Charlie",
    tipo: "perro",
    categoria: "adopcion",
    edad: "3 años",
    tamaño: "Pequeño",
    personalidad: "Tranquilo y cariñoso",
    nivelEnergia: "Bajo",
    requisitos: "Preferiblemente compañía constante en casa",
    ubicacion: "Barranquilla",
    costoMensual: 95000,
  },
  {
    imagen: "./assets/dogs/perro5.webp",
    nombre: "Daisy",
    tipo: "perro",
    categoria: "adopcion",
    edad: "2 años",
    tamaño: "Grande",
    personalidad: "Protectora y leal",
    nivelEnergia: "Moderado",
    requisitos: "Espacio amplio y dueño con experiencia",
    ubicacion: "Bucaramanga",
    costoMensual: 130000,
  },
  {
    imagen: "./assets/dogs/perro6.webp",
    nombre: "Finn",
    tipo: "perro",
    categoria: "adopcion",
    edad: "1 año",
    tamaño: "Grande",
    personalidad: "Activo y juguetón",
    nivelEnergia: "Muy alto",
    requisitos: "Rutina diaria de ejercicio y socialización",
    ubicacion: "Pereira",
    costoMensual: 135000,
  },

  // Mascotas para adopción - Gatos
  {
    imagen: "./assets/cats/gato1.webp",
    nombre: "Luna",
    tipo: "gato",
    categoria: "adopcion",
    edad: "1 año",
    tamaño: "Mediano",
    personalidad: "Energética y juguetona",
    nivelEnergia: "Muy alto",
    requisitos: "Ambiente enriquecido y tiempo de juego diario",
    ubicacion: "Manizales",
    costoMensual: 90000,
  },
  {
    imagen: "./assets/cats/gato2.webp",
    nombre: "Milo",
    tipo: "gato",
    categoria: "adopcion",
    edad: "1 año",
    tamaño: "Pequeño",
    personalidad: "Curioso y juguetón",
    nivelEnergia: "Muy alto",
    requisitos: "Hogar seguro sin acceso al exterior",
    ubicacion: "Armenia",
    costoMensual: 85000,
  },
  {
    imagen: "./assets/cats/gato3.webp",
    nombre: "Nina",
    tipo: "gato",
    categoria: "adopcion",
    edad: "2 años",
    tamaño: "Pequeño",
    personalidad: "Territorial y protectora",
    nivelEnergia: "Moderado",
    requisitos: "Ser el único gato del hogar",
    ubicacion: "Ibagué",
    costoMensual: 80000,
  },
  {
    imagen: "./assets/cats/gato4.webp",
    nombre: "Oreo",
    tipo: "gato",
    categoria: "adopcion",
    edad: "1 año",
    tamaño: "Pequeño",
    personalidad: "Activo y juguetón",
    nivelEnergia: "Muy alto",
    requisitos: "Hogar con juguetes y rascadores",
    ubicacion: "Cúcuta",
    costoMensual: 88000,
  },
  {
    imagen: "./assets/cats/gato5.webp",
    nombre: "Pumpkin",
    tipo: "gato",
    categoria: "adopcion",
    edad: "2 años",
    tamaño: "Pequeño",
    personalidad: "Tranquila y cariñosa",
    nivelEnergia: "Bajo",
    requisitos: "Ambiente tranquilo, sin niños pequeños",
    ubicacion: "Villavicencio",
    costoMensual: 82000,
  },
  {
    imagen: "./assets/cats/gato6.webp",
    nombre: "Riley",
    tipo: "gato",
    categoria: "adopcion",
    edad: "1 año",
    tamaño: "Pequeño",
    personalidad: "Curioso y juguetón",
    nivelEnergia: "Alto",
    requisitos: "Ventanas seguras y tiempo de juego diario",
    ubicacion: "Neiva",
    costoMensual: 87000,
  },

  // Mascotas para apadrinar - Perros
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar1.jpg",
    nombre: "Maximo",
    edad: "5 años",
    tipo: "perro",
    categoria: "apadrinar",
    necesidad: "Necesita un tratamiento constante para su piel delicada y vitaminas que lo ayuden a recuperar su energía y brillo.",
    nivelEnergia: "Alto",
    valorMensual: 50000,
    impacto: "Con tu apoyo, Maximo podrá llevar una vida sin dolor y volver a correr con alegría."
  },
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar2.jpg",
    nombre: "Moon",
    tipo: "perro",
    categoria: "apadrinar",
    edad: "3 años",
    necesidad: "Requiere alimento especializado y medicación para aliviar sus articulaciones y mejorar su movilidad.",
    nivelEnergia: "Moderado",
    valorMensual: 45000,
    impacto: "Tu ayuda permitirá que Moon recupere su vitalidad y disfrute sin dolor de cada día."
  },
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar3.jpg",
    nombre: "Coco",
    tipo: "perro",
    categoria: "apadrinar",
    edad: "4 años",
    necesidad: "Está en proceso de recuperación tras una cirugía por un accidente y necesita cuidados especiales.",
    nivelEnergia: "Bajo",
    valorMensual: 50000,
    impacto: "Gracias a tu apadrinamiento, Coco podrá sanar completamente y volver a confiar en el amor humano."
  },
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar4.jpg",
    nombre: "Simba",
    tipo: "perro",
    categoria: "apadrinar",
    edad: "6 años",
    necesidad: "Lucha con una enfermedad en la piel que necesita tratamiento continuo y cuidados especiales.",
    nivelEnergia: "Muy alto",
    valorMensual: 50000,
    impacto: "Con tu apadrinamiento, Simba tendrá el alivio que necesita para sentirse cómodo y feliz."
  },
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar5.jpg",
    nombre: "Rex",
    tipo: "perro",
    categoria: "apadrinar",
    edad: "9 años",
    necesidad: "Por su edad avanzada, necesita una dieta especial y supervisión constante para asegurar su bienestar.",
    nivelEnergia: "Alto",
    valorMensual: 50000,
    impacto: "Tu apadrinamiento le dará a Rex una vejez digna y llena de cariño."
  },
  {
    imagen: "./assets/Apadrinar/dog/DogApadrinar6.jpg",
    nombre: "Bruno",
    tipo: "perro",
    categoria: "apadrinar",
    edad: "3 años",
    necesidad: "Se encuentra en rehabilitación por una lesión en su patita y requiere fisioterapia regular.",
    nivelEnergia: "Moderado",
    valorMensual: 50000,
    impacto: "Gracias a ti, Bruno podrá recuperar su movilidad y volver a correr como antes."
  },

  // Mascotas para apadrinar - Gatos
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar1.jpg",
    nombre: "Millow",
    edad: "2 años",
    tipo: "gato",
    categoria: "apadrinar",
    necesidad: "Requiere una dieta especial y suplementos diarios para fortalecer su sistema inmunológico.",
    nivelEnergia: "Moderado",
    valorMensual: 40000,
    impacto: "Con tu apoyo, Millow podrá crecer fuerte y saludable."
  },
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar2.jpg",
    nombre: "Felix",
    tipo: "gato",
    categoria: "apadrinar",
    edad: "2 años",
    necesidad: "Está recuperándose de una cirugía ocular y necesita seguimiento médico constante.",
    nivelEnergia: "Alto",
    valorMensual: 50000,
    impacto: "Tu ayuda será clave para que Felix vuelva a ver el mundo con claridad."
  },
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar3.jpg",
    nombre: "Aslan",
    tipo: "gato",
    categoria: "apadrinar",
    edad: "10 años",
    necesidad: "Por su edad, requiere controles médicos frecuentes y una dieta que le brinde vitalidad.",
    nivelEnergia: "Bajo",
    valorMensual: 50000,
    impacto: "Tu apadrinamiento asegurará que Aslan tenga una vida tranquila y digna en sus años dorados."
  },
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar4.jpg",
    nombre: "Simón",
    tipo: "gato",
    categoria: "apadrinar",
    edad: "5 años",
    necesidad: "Tiene problemas respiratorios crónicos que necesitan tratamiento y un entorno controlado.",
    nivelEnergia: "Muy alto",
    valorMensual: 50000,
    impacto: "Con tu apoyo, Simón podrá respirar mejor y vivir más cómodo."
  },
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar5.jpg",
    nombre: "Lucy",
    tipo: "gato",
    categoria: "apadrinar",
    edad: "4 años",
    necesidad: "Sufre una condición cardíaca que requiere medicación diaria para mantenerla estable.",
    nivelEnergia: "Alto",
    valorMensual: 50000,
    impacto: "Tu apadrinamiento será su esperanza para vivir más tiempo con calidad."
  },
  {
    imagen: "./assets/Apadrinar/cat/CatApadrinar6.jpg",
    nombre: "Oliver",
    tipo: "gato",
    categoria: "apadrinar",
    edad: "6 años",
    necesidad: "Necesita atención odontológica especializada para comer sin dolor.",
    nivelEnergia: "Moderado",
    valorMensual: 50000,
    impacto: "Con tu ayuda, Oliver podrá alimentarse bien y vivir sin molestias."
  },
];

export default animalesData;
